spring:
  application:
    name: "cards"
  datasource:
    url: jdbc:mysql://localhost:3307/cards
    username: root
    password: root
  jpa:
#    hibernate:
#      ddl-auto: update
    open-in-view: false
    show-sql: true
  sql:
    init:
      mode: always

  profiles:
    active: "prod"
  config:
    import: "optional:configserver:http://localhost:8071/"

#  rabbitmq:
#    host: localhost
#    port: 5672
#    username: guest
#    password: guest

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

server:
  port: 8070

management:
  endpoints:
    web:
      exposure:
        include: "*"
